

def createTable(ticker, conn):
    cur = conn.cursor()

    query = f"""

                CREATE TABLE {ticker} (
                    {ticker}Id INTEGER PRIMARY KEY AUTOINCREMENT,
                    date TEXT,
                    previous_close NUMERIC,
                    open_value NUMERIC,
                    bid TEXT,
                    ask TEXT,
                    days_range TEXT,
                    week_range TEXT,
                    volume NUMERIC,
                    avg_volume NUMERIC,
                    market_cap NUMERIC,
                    beta NUMERIC,
                    pe_ratio NUMERIC,
                    eps NUMERIC,
                    earnings_date TEXT,
                    dividend_yield TEXT,
                    ex_dividend_date TEXT,
                    year_target_est NUMERIC,
                    _Market_Cap__intraday_ TEXT,
                    _Enterprise_Value TEXT,
                    _Trailing_P_E NUMERIC,
                    _Forward_P_E NUMERIC,
                    _PEG_Ratio__5_yr_expected_ NUMERIC,
                    _Price_Sales__ttm_ NUMERIC,
                    _Price_Book__mrq_ NUMERIC,
                    _Enterprise_Value_Revenue NUMERIC,
                    _Enterprise_Value_EBITDA NUMERIC,
                    _Beta__5Y_Monthly_ NUMERIC,
                    _52_Week_Change TEXT,
                    _S_P500_52_Week_Change TEXT,
                    _52_Week_High NUMERIC,
                    _52_Week_Low NUMERIC,
                    _50_Day_Moving_Average NUMERIC,
                    _200_Day_Moving_Average NUMERIC,
                    _Avg_Vol__3_month_ TEXT,
                    _Avg_Vol__10_day_ TEXT,
                    _Shares_Outstanding TEXT,
                    _Implied_Shares_Outstanding TEXT,
                    _Float TEXT,
                    _perc_Held_by_Insiders TEXT,
                    _perc_Held_by_Institutions TEXT,
                    _Shares_Short TEXT,
                    _Short_Ratio NUMERIC,
                    _Short_perc_of_Float TEXT,
                    _Short_perc_of_Shares_Outstanding TEXT,
                    _Shares_Short_prior TEXT,
                    _Forward_Annual_Dividend_Rate NUMERIC,
                    _Forward_Annual_Dividend_Yield TEXT,
                    _Trailing_Annual_Dividend_Rate NUMERIC,
                    _Trailing_Annual_Dividend_Yield TEXT,
                    _5_Year_Average_Dividend_Yield NUMERIC,
                    _Payout_Ratio TEXT,
                    _Dividend_Date TEXT,
                    _Ex_Dividend_Date TEXT,
                    _Last_Split_Factor TEXT,
                    _Last_Split_Date TEXT,
                    _Fiscal_Year_Ends TEXT,
                    _Most_Recent_Quarter__mrq_ TEXT,
                    _Profit_Margin TEXT,
                    _Operating_Margin__ttm_ TEXT,
                    _Return_on_Assets__ttm_ TEXT,
                    _Return_on_Equity__ttm_ TEXT,
                    _Revenue__ttm_ TEXT,
                    _Revenue_Per_Share__ttm_ NUMERIC,
                    _Quarterly_Revenue_Growth__yoy_ TEXT,
                    _Gross_Profit__ttm_ TEXT,
                    _EBITDA TEXT,
                    _Net_Income_Avi_to_Common__ttm_ TEXT,
                    _Diluted_EPS__ttm_ NUMERIC,
                    _Quarterly_Earnings_Growth__yoy_ TEXT,
                    _Total_Cash__mrq_ TEXT,
                    _Total_Cash_Per_Share__mrq_ NUMERIC,
                    _Total_Debt__mrq_ TEXT,
                    _Total_Debt_Equity__mrq_ TEXT,
                    _Current_Ratio__mrq_ NUMERIC,
                    _Book_Value_Per_Share__mrq_ NUMERIC,
                    _Operating_Cash_Flow__ttm_ TEXT,
                    _Levered_Free_Cash_Flow__ttm_ TEXT
                );

        """
    
    cur.execute(query)
    conn.commit()